language: python
python:
  - "2.7"
install: "pip install s3cmd"
script: ./cibuild.sh

branches:
  only:
  - master

env:
  global:
  - secure: Qw39Q9HeUTWMKMnwWA6UV01/xdrx6/m2DSSmvXIaqbAwBbdYZKIpjaT15fZgx6Xl+a55fdnYOAHC4tVyz99fX6BYziVGGglKI5p22WhyLkhQVHlVlrENPAmVw7J9ug+FspNnzdaKlzIRx5zVVauPffpEYJ/4slk0jgtjDdOEUW8=
  - secure: VLGooiDqFif4a+sGLD8nJ0k/qlgd3ZKjMFrjrMZ4ZiXTybPs8One/8C8oBz2l0VvT8HBwlp+BoaAaRokVdiTuy13jSZLlxXEf/wVEzJdCYxxRbwbEx+dHYbtSUPzetxjT0XR2OoCUFNbJnwa6624414vdaT5yx618XHA83Zd4j4=
