baseurl = "https://guide.hello.is"
MetaDataFormat = "yaml"


[[menu.main]]
    name = "system"
    pre = "<i class='fa fa-cogs'></i>"
    weight = 1

[[menu.main]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = 2
  
[[menu.main]]
    name = "app"
    pre = "<i class='fa fa-mobile'></i>"
    weight = 3

[[menu.main]]
    name = "sense"
    pre = "<i class='fa fa-bullseye'></i>"
    weight = 4

[[menu.main]]
    name = "sleep pill"
    pre = "<i class='fa fa-bomb'></i>"
    weight = 5

[[menu.main]]
    name = "sleep score"
    pre = "<i class='fa fa-bar-chart-o'></i>"
    weight = 6

[[menu.main]]
    name = "alarm"
    pre = "<i class='fa fa-bell-o'></i>"
    weight = 7
   
[[menu.main]]
    name = "sensors"
    pre = "<i class='fa fa-magnet'></i>"
    weight = 8 
    
[[menu.main]]
    name = "account"
    pre = "<i class='fa fa-user'></i>"
    weight = 9

[[menu.main]]
    name = "third party apps"
    pre = "<i class='fa fa-adn'></i>"
    weight = 10

[[menu.main]]
    name = "safety"
    pre = "<i class='fa fa-medkit'></i>"
    weight = 11
